config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'


  resource :users, controller: 'registrations', only:[:create, :edit, :update] do 
    get '/sign_up',  action: 'new'
  end

  resource :users, controller: 'sessions', only:[] do
    get '/sign_in', action: 'new'
    post '/sign_in', action: 'create'
    delete 'logout', action: 'destroy'
  end

  resources :boards
  

  resource :drivers 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beconmedriver.rb
class Beconmedriver < ApplicationRecord
end

app/models/board.rb
class Board < ApplicationRecord
  validates :title, presence: true
end

app/models/driver.rb
class Driver < ApplicationRecord
  belongs_to :user


  mount_uploader :license, LicenseUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true, format: { with: /[\w]+@([\w-]+\.)+[\w-]{2,4}/ }
  validates :password, presence: true, confirmation: true, length: { minimum: 4 }
  validates :nickname, presence: true

  before_create :encypt_password

  has_one :driver

  def encypt_password
    self.password = Digest::SHA1.hexdigest("a#{self.password}z")
  end

  def self.login(user)
    password = Digest::SHA1.hexdigest("a#{user[:password]}z")
    User.find_by(email: user[:email], password: password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  def session_required
    redirect_to sign_in_users_path, notice: '請先登入會員' if not user_signed_in?
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def new
    @board = Board.new
  end
  
  def create
    @board = Board.new(params_board)
    if @board.save
      redirect_to root_path, notice:'新增成功'
    else
      render :new
    end
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])
    if @board.update(params_board)
      redirect_to root_path, notice:'編輯成功'
    else
      render :new
    end
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    redirect_to root_path, notice:'已刪除'
  end



  private
  def params_board
    params.require(:board).permit(:title)
  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :session_required

  def new
    @driver = Driver.new
  end

  def create
    @driver = current_user.create_driver(params_driver)
    if @driver.save
      current_user.update(role: 'driver')
      redirect_to root_path, notice: '恭喜成為外送員'
    else
      render :new
    end
  end


  private
  def params_driver
    params.require(:driver).permit(:license, :car, :account, :user_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params_user)
    if @user.save
      redirect_to root_path, notice:'註冊成功'
    else
      render :new
    end
  end




  private
  def params_user
    params.require(:user).permit(:email, :password, :password_confirmation, :nickname)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.login(params[:user])
    if user
      session[:user1111] = user.id
      redirect_to root_path, notice: '登入成功'
    else
      redirect_to sign_in_users_path, notice: '登入失敗'
    end
  end

  def destroy
    session[:user1111] = nil
    redirect_to root_path, notice: '已登出'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user1111].present?
      @user111 ||= User.find_by(id: session[:user1111])
    else
      nil
    end
  end

  def user_signed_in?
    if current_user
      return true
    else
      return false
    end
  end
end

app/views/boards/edit.html.erb
<% if @board.errors.any? %>
  <ul>
    <% @board.errors.full_message.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h1>編輯標題</h1>

<%= form_for(@board) do |form| %>

<div>
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div>
  <%= form.submit %>
</div>

<% end %>

app/views/boards/index.html.erb
<%= flash[:notice] %>
<h1>嗨，妳好</h1>


<table>
  <% @boards.each do |board| %>
  <tr>
    <td><%= board.title %></td>
    <td><%= link_to '編輯', edit_board_path(board) %></td>
    <td><%= link_to '刪除', board_path(board), method: 'delete', data: {confirm: '確定刪除？'} %></td>
  </tr>
  <% end %>
</table>

<%= link_to '新增文章', new_board_path %>


<div>
  <% if current_user %>
    <%= current_user.nickname %>
    <%= link_to '登出', logout_users_path, method: 'delete' %>
    <% if current_user.role == 'driver' %>
      <%= link_to '開始外送', '#' %>
    <% else %>
      <%= link_to '成為外送員', new_drivers_path %>
    <% end %>
  <% else %>
    <%= link_to '註冊', sign_up_users_path %>
    <%= link_to '登入', sign_in_users_path %>
  <% end %>
</div>

app/views/boards/new.html.erb
<% if @board.errors.any? %>
  <ul>
    <% @board.errors.full_message.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h1>新增標題</h1>

<%= form_for(@board) do |form| %>

<div>
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div>
  <%= form.submit %>
</div>

<% end %>

app/views/drivers/new.html.erb
<h1>成為外送員</h1>

<%= form_for(@driver) do |form| %>

  <div>
    <%= form.label :license %>
    <%= form.file_field :license %>
  </div>
  <div>
    <%= form.label :car %>
    <%= form.text_field :car %>
  </div>
  <div>
    <%= form.label :account %>
    <%= form.text_field :account %>
  </div>
  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dcard2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>